# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_pb2s.class_pb2 as class__pb2


class ClassControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/class.ClassController/List',
                request_serializer=class__pb2.ClassListRequest.SerializeToString,
                response_deserializer=class__pb2.ClassList.FromString,
                )
        self.GetCommenClasses = channel.unary_unary(
                '/class.ClassController/GetCommenClasses',
                request_serializer=class__pb2.ClassCommenRequest.SerializeToString,
                response_deserializer=class__pb2.ClassList.FromString,
                )


class ClassControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommenClasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=class__pb2.ClassListRequest.FromString,
                    response_serializer=class__pb2.ClassList.SerializeToString,
            ),
            'GetCommenClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommenClasses,
                    request_deserializer=class__pb2.ClassCommenRequest.FromString,
                    response_serializer=class__pb2.ClassList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'class.ClassController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClassController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/class.ClassController/List',
            class__pb2.ClassListRequest.SerializeToString,
            class__pb2.ClassList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCommenClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/class.ClassController/GetCommenClasses',
            class__pb2.ClassCommenRequest.SerializeToString,
            class__pb2.ClassList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
